site_name: oceanobs
pages:
    - Home: ../README.md
    - Installation: installation.md
    - Examples: /examples/index_examples.md
    - Package overview: package.md
    - API reference: api.md
    - News: news.md
theme: readthedocs