site_name: oceanobs
pages:
    - Home: index.md
    - Installation: installation.md
    - Examples: ./examples/index_examples.md
    - Package overview: package.md
    - API reference: api.md
    - Github structure: github_struct.md
    - News: news.md
theme: readthedocs